### ISSUE TITLE
Add ability to resolve patterns for global properties

### ISSUE THREAD

**Issue by felixbarny** [elastic/java-ecs-logging#2]
@pgomulka requested to add global metadata which can be looked up by a pattern. For example the Elasticsearch `node.id`. This would make this library feasible to use inside Elasticsearch itself.

**Comment by pgomulka** [comment]
I was experimenting with this today and I was having trouble to make it work. I might be missing some configuration but the property inserted into this context did not propagate to loggers obtained with `LogManager.getLogger`. See the integration test: https://github.com/elastic/java-ecs-logging/pull/12

Other observation I found
- We rely strongly on pattern converters in Elasticsearch at the moment. It would be great if we could make it more configurable in the lib (java-ecs-logging)
- Exception stactrace at the moment is printed out as a one line string, which is unreadable. Having exception as an additional array field and formatted to multiline would help. Again we have a pattern converter for this in ES, once this work we could use this.
- Adding new field is only possible during configuration. This I think should be extended as we define custom logging messages classes which contain custom fields. The goal would be to have much more messages like this.
https://github.com/elastic/elasticsearch/blob/d7c84e16ef7f3f8e885ab6030fcb1e3038dd3c23/server/src/main/java/org/elasticsearch/index/SearchSlowLog.java#L155
https://github.com/elastic/elasticsearch/blob/7e6d10f4d3e9aa7267d30e835d7ebb7e6f154d6e/server/src/main/java/org/elasticsearch/common/logging/DeprecatedMessage.java
https://github.com/elastic/elasticsearch/blob/7e6d10f4d3e9aa7267d30e835d7ebb7e6f154d6e/server/src/main/java/org/elasticsearch/index/IndexingSlowLog.java#L167
- We also use markers at the moment (though we might refactor this). Without being able to provide a custom pattern for message field, it would be visible there.

Overall It looks very promising and the idea of making a generic ready to use ECS layout is excellent in my opinion.

**Comment by felixbarny** [comment]
Instead of the custom `ESLogMessage`, have you considered using the built-in [`org.apache.logging.log4j.message.StringMapMessage`](https://logging.apache.org/log4j/2.x/manual/messages.html)? That supports serializing as JSON.

**Comment by pgomulka** [comment]
I was looking into this too. I still maintain the old custom formating for
plain text logs.
Also with out of the box json formatting the customisation would be
troublesome.
