### ISSUE TITLE
Filebeat sample config replaces log timestamp

### ISSUE THREAD

**Issue by pnowak85** [elastic/java-ecs-logging#34]
I setup up the logback EscEncoder and filebeat as described in the docs and noticed a strange behavior.
The timestamps in elastic/kibana where not the same as in my json log files (a few milliseconds to minutes off). The timestamp in elastic was always the `indexed/read` timestamp from filebeat but not the actual timestamp from the log line. 

While discussing this with @xeraa, he mentioned the `json.overwrite_keys` property.

Setting this property to `true` fixes this.

Please update the sample docs for the filebeat setup to avoid confusions.

```
json:
    keys_under_root: true
    overwrite_keys: true
```

**Comment by felixbarny** [comment]
Good catch, thanks!

**Comment by pnowak85** [comment]
Thanks for the fast reponse.

Please also update the [With filebeat.yml configuration file](https://github.com/elastic/java-ecs-logging#with-filebeatyml-configuration-file) section

**Comment by xeraa** [comment]
Done in 8fc55533cc38e671dada4ca7908d708af5a67dde

Thanks Peter!
